name: Publish Storybook

on:
  push:
    branches:
      - master

jobs:
  my-job:
    name: My job
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to vxui.surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'vxui.surge.sh'
          project: '.'
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}
